fastlane_require 'dotenv'

# apple_id: email
apple_id = ""

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    Dotenv.overload '../../.env'
    build_app(workspace: "RNStarter.xcworkspace", scheme: "RNStarter")
    upload_to_testflight(
      username: apple_id,
      skip_waiting_for_build_processing: true
    )
    upload_symbols_to_bugsnag(
      api_key: ENV['BUGSNAG_API_KEY']
    )
  end

  desc "Push a new release build to TestFlight"
  lane :release do
    Dotenv.overload '../../.env.production'
    build_app(workspace: "RNStarter.xcworkspace", scheme: "RNStarter (Production)")
    upload_to_testflight(
      username: apple_id,
      skip_waiting_for_build_processing: true
    )
    upload_symbols_to_bugsnag(
      api_key: ENV['BUGSNAG_API_KEY']
    )
  end

end
