name: Lint & Test

on:
  push:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: Lint & Test
        run: |
          yarn lint
          yarn test
